import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useConnectModal } from "@rainbow-me/rainbowkit";
import {
  useAccount,
  useBalance,
  useDisconnect,
  useNetwork,
  usePrepareSendTransaction,
  useSendTransaction,
} from "wagmi";
import { useIsClient } from "usehooks-ts";
import { BigNumber } from "ethers";

export default function Home() {
  const isClient = useIsClient();
  const { openConnectModal } = useConnectModal();
  const { disconnect } = useDisconnect();
  const { isConnected, address } = useAccount();
  const { chain } = useNetwork();
  const { data: balanceData } = useBalance({
    address,
    chainId: chain?.id,
  });
  const { config } = usePrepareSendTransaction({
    request: { to: address || "", value: BigNumber.from("10000000000000000") },
  });
  const { sendTransaction } = useSendTransaction(config);

  return (
    <>
      <Head>
        <title>Connect Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button
          onClick={() => {
            isConnected ? disconnect() : openConnectModal && openConnectModal();
          }}
          className={styles.connectWalletButton}
        >
          {isClient && isConnected ? "Disconnect Wallet" : "Connect Wallet"}
        </button>
        {isClient && isConnected && (
          <>
            <button
              onClick={() => alert(`Chain ID is ${chain?.id}`)}
              className={`outlined ${styles.menuButton}`}
            >
              Get Chain ID
            </button>
            <button
              onClick={() => alert(`Your balance is ${balanceData?.formatted}`)}
              className={`outlined ${styles.menuButton}`}
            >
              Get Balance
            </button>
            <button
              onClick={() => sendTransaction && sendTransaction()}
              className={`outlined ${styles.menuButton}`}
            >
              Send Transaction
            </button>
          </>
        )}
      </main>
    </>
  );
}
